
#Power settings
[power]

	#TestBlock settings
	[power.test_block]
		#Maximum power for the Test Block generator
		#Range: > 0
		maxPower = 100000
		#Power generation per adamant plate
		#Range: > 0
		generate = 1000
		#Power generation to send per tick
		#Range: > 0
		send = 100
		#Ticks per plate
		#Range: > 0
		ticks = 20

